import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import HeroSection from '../components/HeroSection'


export default function Home() {
  return (
    <div>
      <Head>
        <title>CodeTut</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar/>
      <HeroSection/>
      <Footer/>
    </div>
  )
}
